### PR TITLE
Updated bar-dependencies to 1.0.0.4. jnext.so no longer included.

### PR DESCRIPTION
**Pull request by jamesjhedley**
Fixed issue blackberry/BB10-Webworks-Packager#155

### CODE REVIEW

**Comment by jamesjhedley** [comment]
@ishneur Can you please test this with the latest trunk build?

**Comment by ishneur** [comment]
Tested on Windows on trunk build 1207. WebWorks app can be installed and launched and the API smoke test passes.

The only problem is if I try to install an app which I deleted from the device before and which has the same name (but is repackaged with this branch, so it's a new bar), installation fails with this error, probably because there is a leftover folder on the device OS from the previous install:

Info: Sending request: Install
Info: Action: Install
Info: File size: 868239
Info: Installing ...
Info: Processing 868239 bytes
Info: Progress 100%...
Info: Progress 100%...
actual_dname::
actual_id::
actual_version::
result::failure 500 OSError: [Errno 17] File exists

**Comment by ishneur** [comment]
This problem also happens if I:
1. Package an app using this branch and deploy/run it
2. Delete the app manually
3. Re-package the app using this branch again and try to deploy it - I cannot deploy and a similar error happens

The only workaround is to rename the app and then re-package it.

**Comment by jamesjhedley** [comment]
@ishneur I can't seem to reproduce this issue. I am on a slightly older build though (1195). Did you package your application using the old packager first? (I.e. before my change)

**Comment by ishneur** [comment]
I tried both, old packager first and your packager first. Maybe the trunk build makes a difference too.

What I just tried again is:
1. Packaged the app DialogAPI.zip (which I never installed before on my current OS) using the new packager (this branch) and deployed it
2. Deleted it
3. Tried to deploy the same bar without repackaging

I got this error:

Info: Sending request: Install
Info: Action: Install
Info: File size: 806346
Info: Installing ...
Info: Processing 806346 bytes
Info: Progress 100%...
actual_dname::
actual_id::
actual_version::
result::failure 500 OSError: /apps/.new.DialogAPI.testRel_DialogAPI__c75cbb92/na
tive/tire.png: [Errno 2] No such file or directory: '/apps/.new.DialogAPI.testRe
l_DialogAPI__c75cbb92/native/tire.png'

**Comment by nukulb** [comment]
This fix isn't helping this bug. Closing the pull request and not merging.

**Pull request closed without merging**
