### PR TITLE
Pull req - Removed colored output text :(

### PR DESCRIPTION
**Pull request by jamesjhedley**
Removing the colored output text in the packager to fix some Ripple issues.

### CODE REVIEW

**Comment by jeffheifetz** [comment]
Code Review Completed

**Comment by rcruz** [comment]
Code Review Complete.  Runs as expected.

**Comment by adrianlee** [comment]
Can you grab the playbook and my torch from my drawers and keep them in safe place. Thanks
Sent from my BlackBerry device on the Rogers Wireless Network

**Comment by erhorim** [comment]
Ok, they're in my safe.

-----Original Message-----

**Pull request merged**
