### PR TITLE
Fixing wrong paths for wrench node module

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by ericpearson** [comment]
r+

**Comment by jeffheifetz** [comment]
@tracyli @ishneur  Super quick smoke test please

**Comment by tracyli** [comment]
tested with http://ci0000003863287:8080/hudson/job/BB10-Webworks-Packager-next-pathFix/1/: smoke test passed.

**Comment by jeffheifetz** [comment]
ready to merge

**Comment by ejzn** [comment]
merged manually.

**Pull request closed without merging**
