### PR TITLE
Added support for disabling childBrowser (childWebView) behaviour

### PR DESCRIPTION
**Pull request by derek-watson**
Fixes the issue blackberry/BB10-WebWorks-Framework#230

Framework pull request - blackberry-webworks/BB10-WebWorks-Framework#195

### CODE REVIEW

**Comment by jeffheifetz** [comment]
@tracyli @ishneur Please test this. There is a page under the manual test app that pretty clearly sets expectations

**Comment by nukulb** [comment]
where is the framework pull request for htis?

**Comment by derek-watson** [comment]
https://github.com/blackberry-webworks/BB10-WebWorks-Framework/pull/195

**Comment by nukulb** [comment]
obviously needs a rebase which will remove the submodule.
more importantly once you build the webplatform it will generate a ui.html, which needs to be manually be put into the framework as it needs to be loaded from within the bar

**Comment by nukulb** [comment]
that was the wrong place for this comment. Meant to say it in the framework pull request.

**Comment by jeffheifetz** [comment]
@derek-watson Please rebase

**Comment by ishneur** [comment]
I added the following into the test app config.xml:
`<feature id="blackberry.app" required="true" version="1.0.0.0">
        <param id="childBrowser" value="disable" />
    </feature>`

When I click on a _blank target, the page still opens in a child webview. I used the packager from here: http://ci0000003863287:8080/hudson/job/BB10-Webworks-Packager-twg_childWebView/.

Is this the right way of disabling it?

**Comment by ejzn** [comment]
ping... @derek-watson per @ishneur 's question

**Comment by derek-watson** [comment]
Rebased.

@erikj54, @ishneur The description for the issue had a typo. Please see https://github.com/blackberry/BB10-WebWorks-Framework/issues/230#issuecomment-9910878, but the gist is that you should use param name instead of param id, like so
`
<feature id="blackberry.app" >
<param name="childBrowser" value="disable" />
</feature>`

**Comment by ishneur** [comment]
There was no new CI build so I clicked Build Now on CI for that branch. It started building but the new build failed.

I tested with the previous CI build and it worked when using `<param name="childBrowser" value="disable" />` - child webview is disabled.

**Comment by derek-watson** [comment]
Did I cause the build to fail with my rebase?

**Comment by ishneur** [comment]
@derek-watson Maybe, since it failed after the rebase.

**Comment by derek-watson** [comment]
@ishneur I have fixed some failing tests, but I still have two tests failing. These two tests also fail on the next branch, so I don't think I can address them.

Can you let me know if the next CI build passes?

**Comment by nukulb** [comment]
building now

**Comment by nukulb** [comment]
Its built now.

**Comment by nukulb** [comment]
success

**Comment by derek-watson** [comment]
:+1:

**Comment by ishneur** [comment]
@derek-watson Using the latest build, child webview doesn't work unless I replace the framework with the one from the branch twg_childWebViewRebase. When I click on _blank targets nothing happens, but when I replaced the framework it started working.

**Comment by ishneur** [comment]
When I add `<param name="childBrowser" value="disable" />` to config.xml, child webview is disabled as expected. This was also tested after replacing the framework in this build.

**Pull request closed without merging**
