### PR TITLE
Updating maven to use wwe as a bash script instead of the web launcher executable

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by erhorim** [comment]
Workaround needed:
1)rename jnext.so to jnext.so2
2)remove #!/bin/sh in wwe

After above steps, app can be launched using native weblauncher.
Without step2, app cannot be launched and error "Unable to start <app name> due to error 2" appears in device.

**Comment by nukulb** [comment]
@jeffheifetz and @adrianlee are looking into the new line break.

**Comment by tracyli** [comment]
Tested in mac with build http://mac-ci:9000/job/BB10-Webworks-Packager-next-maven-wwe-script/1/ but "Unable to start due to error 2" occurred when launching an application.

**Comment by adrianlee** [comment]
@erhorim @tracyli There is a new build which you can test [here](http://mac-ci:9000/job/BB10-Webworks-Packager-next-maven-wwe-script/)

The workaround with renaming jnext.so is still required.

You should no longer see the Error 2 when launching the app.

**Comment by tracyli** [comment]
Tested the simulator and insecure device using the application generated from mac and windows with build http://mac-ci:9000/job/BB10-Webworks-Packager-next-maven-wwe-script/11/ and no issue is found.

**Comment by nukulb** [comment]
@tohman Why did you close this pull request?
And what is your change, you seem to be updating the hash, what is this hash?

**Comment by tohman** [comment]
I don't know how it related but i did a commit to the totally different branch next-fix-18-addremovoeevent-reenter-threshold-trigger without even knowing about existence of this pull request. I think because issue here is #18 and my branch name has 18 in it made it to happen.

**Comment by erhorim** [comment]
In Win, workaround needed:
1)rename jnext.so to jnext.so2

After above step, app can be launched using native weblauncher in insecure device with appropriate OS.

SV&V tests complete, please merge.

**Pull request merged**
