### PR TITLE
Changed packager maven scripts so it can propagate a change of version to the Framework

### PR DESCRIPTION
**Pull request by ronalag**
Made changes to the maven scripts of the packager so it can trigger an update of the Framework

@EricLeiLi @tohman

### CODE REVIEW

**Comment by EricLeiLi** [comment]
r+

**Comment by EricLeiLi** [comment]
Sorry, I shouldn't have closed it and the other pull request because they are actually different repositories.

**Comment by EricLeiLi** [comment]
Please merge it.

**Comment by ishneur** [comment]
I tested this on Windows using SCM build 1.0.0.3 and it worked. Is there any other particular packager build that it should be tested with? The version of webworks.js is 1.0.0.7. Does it correspond to a specific build?

Also, there is no unit test for this pull request. Should there be one, or is functional/manual testing enough in this case?

**Comment by ishneur** [comment]
Actually, the latest SCM build is 1.0.0.7, which explains the version of webworks.js. I tested it with SCM 1.0.0.7 and it works as well.

When I use an older webworks.js from SCM builds 1.0.0.2 and 1.0.0.3 and build those apps with SCM build 1.0.0.7, they still work, so I don't think there is a negative case. The only case in which the apps/APIs don't work is if I use a much older webworks.js from an older feature build.

Testing completed on both Windows and Mac.

**Comment by nukulb** [comment]
@ronalag Why do you have a personal fork of this repo?

**Comment by nukulb** [comment]
delivers feature blackberry/BB10-Webworks-Packager#117

**Pull request merged**
