### PR TITLE
Check for the existance of config.xml before opening

### PR DESCRIPTION
**Pull request by cdelcol**
Fixes issue blackberry/BB10-Webworks-Packager#193
Includes a scope fix in un-related unit test

### CODE REVIEW

**Comment by nukulb** [comment]
R+

**Comment by cdelcol** [comment]
@haahmad Nukul suggested you might have a bit of time to give this a test? The scoping fix is actually why this should get done sooner rather than later.

This has not been run yet on a Windows machine so that should be included.

**Comment by haahmad** [comment]
I don't see any ci builds for this on hudson.

**Comment by cdelcol** [comment]
I forced push with a new commit message to try to re-trigger hudson. No other changes.

**Comment by cdelcol** [comment]
@haahmad I manually created the job, and started it. There is now a successful build available.

**Comment by haahmad** [comment]
Tested on Windows XP and Mac, I am seeing the expected behavior.

**Comment by nukulb** [comment]
merged manually

**Pull request closed without merging**
