### PR TITLE
Pull Req: Empty INFO and ERROR messages appear in the output during packaging

### PR DESCRIPTION
**Pull request by adrianlee**
Fixes Issue #107
- stdout and stderr logs from the native packager were introducing the line feed and carriage return characters which make it into our output when packaging.

### CODE REVIEW

**Comment by adrianlee** [comment]
@rwmtse @ishneur

**Comment by rwmtse** [comment]
Code looks good to me.

**Comment by ishneur** [comment]
Verification passed on Windows XP and 7 using CI build http://mac-ci:9000/job/BB10-Webworks-Packager-next-issue107/2/.

No empty INFO and ERROR messages are printed out anymore.

I don't currently have a Mac so wasn't able to verify it on Mac yet, and will also need to verify it in Ripple.

**Comment by nukulb** [comment]
@tracyli  - can you test this on a MAC please?

**Comment by ishneur** [comment]
Verification passed in Ripple too.

**Comment by nukulb** [comment]
@issp - since you have the MAC can you test this please

**Comment by issp** [comment]
Verification passed on Mac for build#: "http://mac-ci:9000/job/BB10-Webworks-Packager-next-issue107/"

**Comment by nukulb** [comment]
@themainguru - can you test Ripple before we fold this down?

**Comment by jengee** [comment]
Looks good to me from Ripple standpoint. I'm impressed. BB10 packager can handle numbers,non-alpha characters and spaces that Ripple throws at it.

**Pull request merged**
