### PR TITLE
Fixes blackberry/BB10-Webworks-Packager#183 - removed app id validation

### PR DESCRIPTION
**Pull request by rwmtse**
@jkeshavarzi Please code review.

### CODE REVIEW

**Comment by jamesjhedley** [comment]
There are a lot of validation scenarios we are no longer checking for by removing this (see below).
@nukulb are we sure we want to solve this issue this way?

1)Fails when id is undefined
2)Fails when id begins with a number
3)Fails when id contains a non [a-zA-Z0-9] character
4)Fails when id starts with a space
5)Fails when id ends with a space

**Comment by nukulb** [comment]
Yes
~Nukul

**Comment by jamesjhedley** [comment]
r+

**Comment by jamesjhedley** [comment]
Tested and everything works as expected.
The user will now get an error from the native-packager when their ID is invalid.

`[ERROR]   Error: Attribute Package-Name: value has invalid characters or syntax: 1com.rim.test 
[ERROR]   Native Packager exception occurred`

**Comment by jamesjhedley** [comment]
Merged manually.

**Pull request closed without merging**
