### PR TITLE
Pull req - Temp fix for GHI #131

### PR DESCRIPTION
**Pull request by jamesjhedley**
This is a temporary fix to allow Framework pull req 34 to be folded without problems [https://github.com/blackberry-webworks/BB10-WebWorks-Framework/pull/34]

### CODE REVIEW

**Comment by nukulb** [comment]
code review complete

**Comment by tracyli** [comment]
tested in windows and mac with build http://mac-ci:9000/job/BB10-Webworks-Packager-next-TempFix/1/: issue95 has been fixed and the issue of 'Error occurs when invoking connection api" has been fixed.

**Comment by nukulb** [comment]
lets make sure we fold this after folding blackberry-webworks/BB10-WebWorks-Framework#34. Once the other Pull Request is folded, lets make sure the Framework hash is updated as a part of this pull request.

**Comment by nukulb** [comment]
merged manually

**Pull request closed without merging**
