### PR TITLE
Pull Req - Fix for issue #12 [Native Packager exception occurs if the version attribute contains 4 digits]

### PR DESCRIPTION
**Pull request by jamesjhedley**
Fixes Blackberry GHI #12 - Native Packager exception occurs if the version attribute contains 4 digits

### CODE REVIEW

**Comment by jamesjhedley** [comment]
You mean build version? Yes, we should.
It looks like our regex validation for version is not working properly!

**Comment by erhorim** [comment]
Tests suspended until further fixes.

**Comment by jamesjhedley** [comment]
I have fixed the broken regex, please continue testing.

**Comment by erhorim** [comment]
If version="1.2.3.4", and compile app by bbwp app.zip -o dir, it currently automatically attempts to sign app but fails:
12:11:59 - INFO  - Populating application source
12:11:59 - INFO  - Parsing config.xml
12:11:59 - INFO  - Generating output files
12:12:00 - INFO  - Info: Package created: C:\WebWorks\BB10 Beta1\Test\BB10\GHI12\simulator\GHI12.bar
12:12:00 - INFO  -
12:12:00 - INFO  - Info: Package created: C:\WebWorks\BB10 Beta1\Test\BB10\GHI12\device\GHI12.bar
12:12:00 - INFO  -
12:12:01 - ERROR - Error: Failed to decrypt keystore, invalid password
12:12:01 - ERROR - Native Packager exception occurred

If -g is not specified, should it automatically attempts to sign app?

**Comment by jamesjhedley** [comment]
No it shouldn't. There is an issue with one of the node modules we use that causes this problem.
Tracy created an issue for this the other day [https://github.com/blackberry/BB10-Webworks-Packager/issues/86].

**Comment by kwhatmough** [comment]
Code review complete

**Comment by erhorim** [comment]
Tests passed in Windows based on the following test cases:
1) Sign with -g(incorrect password) no -b (4-digit version), app compiled but signing failed
2) Sign with -g(correct password) no -b (4-digit version), app signed successfully, 4th digit used as buildId and must be unique.
3) Sign with -g(correct password) no -b (same 4-digit version), app compiled but signing failed as not unique version
4) Sign with -g(correct password) -b <num> (4-digit version), app signed successfully, -b <num> used as buildId and must be unique.
5) Sign with -g(correct password) -b <same num> (4-digit version), app compiled but signing failed as not unique buildId

**Comment by tracyli** [comment]
Test is done in Mac with 'build http://mac-ci:9000/job/BB10-Webworks-Packager-next-fix12/3/' and 5 senarios mentioned above got passed.

**Comment by erhorim** [comment]
SV&V tests complete, please merge.

**Pull request merged**
