### PR TITLE
Adding new rim:header attribute to the packager parsing

### PR DESCRIPTION
**Pull request by ejzn**
Fixes Issue: blackberry/BB10-WebWorks-Framework#333

### CODE REVIEW

**Comment by ishneur** [comment]
Tested this packager branch together with the framework branch from blackberry-webworks/BB10-WebWorks-Framework#240 and rim:header works correctly. More detailed test results are posted in the framework pull request.

**Comment by ejzn** [comment]
@rcruz Can you please review?

**Comment by rcruz** [comment]
r+

**Comment by rcruz** [comment]
r+ after changes

**Comment by ejzn** [comment]
Just awaiting sign off from @ishneur

**Pull request merged**
