### PR TITLE
Change output location of webplatform.js and i18n.js to the app root

### PR DESCRIPTION
**Pull request by rcruz**

### CODE REVIEW

**Comment by rcruz** [comment]
Still need to update Framework commit hash when the Framework change goes in

**Comment by jeffheifetz** [comment]
Why are we doing this, and doesn't it affect the bootstrap?

**Comment by rcruz** [comment]
We are doing it to support platform:/// protocol. When the files no longer exist in the bar, they will fall back on the device location and find the correct file. It does affect bootstrap, a change in framework on compileUiRemoval branch takes care of it

**Comment by nukulb** [comment]
I think this merged already 
@rcruz - close this

**Pull request closed without merging**
