### PR TITLE
Fixing issue with unit test during SCM builds

### PR DESCRIPTION
**Pull request by jamesjhedley**

### CODE REVIEW

**Comment by jamesjhedley** [comment]
CI build passed. A quick r+ should be enough for this.

**Comment by ericpearson** [comment]
r+ but how can I test it?

**Comment by jamesjhedley** [comment]
@pagey 
-Can run jake test or verify in the CI build (which passed)
-On SCM side, we have already had a SCM build pass with this code, so we should be good on that front.

**Comment by nukulb** [comment]
merged manaully

**Pull request closed without merging**
