### PR TITLE
enable-flash feature should be ignored in access elements

### PR DESCRIPTION
**Pull request by jamesjhedley**
Fixes blackberry/BB10-Webworks-Packager#181

### CODE REVIEW

**Comment by jamesjhedley** [comment]
@rwmtse code review? :) It's small and related to my last change.

**Comment by rwmtse** [comment]
Code review complete

**Comment by tracyli** [comment]
tested in windows&mac with http://ci0000003863287:8080/hudson/job/BB10-Webworks-Packager-next-fix181/: this issue has been fixed.

**Comment by jamesjhedley** [comment]
Merged manually

**Pull request closed without merging**
