### PR TITLE
Node v0.8.14 support + removed fsext dependency

### PR DESCRIPTION
**Pull request by jamesjhedley**
Node v0.8.14 support
-Updated Wrench to 1.3.9
-Updated Windows/Mac node binaries to v0.8.14

Refactored code
-path.existsSync --> fs.existsSync
-path.exists --> fs.exists

When testing, please do a full regression.

### CODE REVIEW

**Comment by jamesjhedley** [comment]
I have included a commit to remove the fsext node module from the Packager and the necessary code refactoring to do so. I am including this here so it can be tested as part of the full regression that will be done on this branch.

**Comment by jamesjhedley** [comment]
Rebased. This is ready for testing when you get a chance @tracyli.

**Comment by tracyli** [comment]
tested in mac with http://ci0000003863287:8080/hudson/job/BB10-Webworks-Packager-next-node-0.8.14/5/: configure & jake work fine with node0.8.14; smoke test passed; apis including app,bbm,event,filetransfer,push,connection,system work as expected; bbwpignore worked as expected; automated functional test worked 

tested in winxp: configure & jake work fine with node0.8.14; smoke test passed; automated functional test worked 

please note:
1.automated functional test in winxp used a workaround method
2.in automated functional test: remoteFunctionCall and crossOrigin test suites failed as usual

**Comment by ericpearson** [comment]
needs rebase :)

**Comment by jamesjhedley** [comment]
@pagey You were reviewing this right? Can i get a r+?

**Comment by nukulb** [comment]
@EricLeiLi  - you will need to update node on the qnx build server for the test app. Please let me know when you are ready and then we can fold this.

**Comment by EricLeiLi** [comment]
I am still investigating why the smoke test app will freeze the device. Until I figure it out, I can tell whether node 0.8.14 will work or not. However, I believe 0.8.14 should be ok. If you cannot wait, I suggest you just merge it.

**Comment by ericpearson** [comment]
This fixes issue #203

**Comment by nukulb** [comment]
@jkeshavarzi open to blackberry:next

**Pull request closed without merging**
