### PR TITLE
Signing support [UserStory - As a WebWorks developer, I can sign my bar ...

### PR DESCRIPTION
**Pull request by nukulb**
...file for distribution in AppWorld]

Unit tests have also been created.

Detailed list of changes:
-Updated command-line interface/session object to accept and store signing parameters from user
-Updated native packager call options file to include parameters to sign the bar (if specified)
-Error handling [Handle missing keys]
-Signing-helper class created to get signing key location (Per Eric Li)

Comments were lost due to moving the repo to blackberry
https://github.com/blackberry/BB10-Webworks-Packager/pull/76

### CODE REVIEW

**Comment by EricLeiLi** [comment]
The codes are fine, but I think we should finish the ToDo(s) before we can merge the request.

**Comment by jamesjhedley** [comment]
The TODO i put in the packager-validator is more of a suggestion for the future implementation of that class (which will be when we tackle validation).

The other TODO i will remove when i submit my other CL for the version/build id fix.

**Comment by ishneur** [comment]
SV&V testing completed on Windows 7. Tested negative and positive signing scenarios as well as installing a signed application through App World.

Note that currently, in order to sign an app, a build ID must be provided using the -b parameter (e.g. bbwp test.zip -g password -b 10), otherwise the app is not signed.

Also opened an issue regarding unclear error messages when either the .csk or the .db file is missing: https://github.com/blackberry/BB10-Webworks-Packager/issues/84.

Other than that, no issues found.

**Comment by jamesjhedley** [comment]
Hey @ishneur i double checked with @kwallis and we do in fact still want to force the user to enter --buildId each time.

**Comment by erhorim** [comment]
Similar positive and negative tests completed in WinXP, all tests passed.

**Comment by tracyli** [comment]
Test are done on Mac with build5 for BB10-Webworks-Packager-next-signingSupport.

**Comment by EricLeiLi** [comment]
r+

**Pull request merged**
