### PR TITLE
Next xml rename

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by nukulb** [comment]
@jkeshavarzi - code review

**Comment by jamesjhedley** [comment]
r+

**Comment by nukulb** [comment]
@jkeshavarzi - can you test it as well please?

**Comment by nukulb** [comment]
@jeffheifetz - squash please

**Comment by jamesjhedley** [comment]
Smoke test passed.

**Comment by jamesjhedley** [comment]
Is there an issue# for this @jeffheifetz?

**Comment by jamesjhedley** [comment]
Smoke test passed on Windows as well.

Merged manually.

**Pull request closed without merging**
