### PR TITLE
Fixed issue #104:  packager output in incorrect directory

### PR DESCRIPTION
**Pull request by miwong**
Fixes issue #104 (blackberry/BB10-Webworks-Packager/issues/104)

Packager now places output bar files into the directory of the .zip, by default.

### CODE REVIEW

**Comment by jamesjhedley** [comment]
Code review complete.

**Comment by nukulb** [comment]
@miwong - rebase please - the session file was changed by another Pull request so you might need to merge

**Comment by issp** [comment]
Verification passed on Windows and Mac. Loaded bar file by Igor in device and the widget launches without any issues.

**Comment by miwong** [comment]
Rebase done.

**Pull request closed without merging**
