### PR TITLE
Pull Req: Validating of widget packaging doesn't give a compilation error, if <feature> element is provided for access URI specified with "*"

### PR DESCRIPTION
**Pull request by adrianlee**
This pull request includes the bug fix & unit test for issue blackberry/BB10-Webworks-Packager#58

### CODE REVIEW

**Comment by ishneur** [comment]
SV&V verification:

The current error message is: "[Error: Invalid config.xml - no tags are allowed for this element]".
The actual error message should be: "Invalid config.xml - no `<feature>` tags are allowed for this `<access>` element" - This is the error message in Tumbler/Snarf.

**Comment by jamesjhedley** [comment]
@adrianlee You should rebase this request with next before it gets tested

**Comment by ishneur** [comment]
SV&V verification passed on Windows. The error message is now correct.

**Comment by jamesjhedley** [comment]
I spent some time looking into this and the Validator module is doing some weird stuff that is causing problems for us with this scenario. 

I have uploaded a cleaner solution that does not use the Validator.

**Comment by jamesjhedley** [comment]
Code review complete

**Comment by ishneur** [comment]
Retested on Windows. Verification passed.

**Comment by erhorim** [comment]
SV&V tests passed in Mac.
Please merge.

**Pull request merged**
