### PR TITLE
package versioned webworks.js from Framework/clientFiles as chrome/webwo...

### PR DESCRIPTION
**Pull request by bryanhiggins**
Packager finds webworks-\* in Framework/clientFiles and if exactly one file is found, moves it to chrome/webworks.js in the target.

A warning is logged if the application file overwrites the framework file and an error is logged if there are 0 or >1 files found in clientFiles.

### CODE REVIEW

**Comment by jeffheifetz** [comment]
I thought the point of this was to inject the file and no longer require users to include webworks.js. I think the packager should throw a warning/error is there is a webworks-X.js file no matter what and should always be injecting its own file from the Framework.

**Comment by ejzn** [comment]
I think this is a okay change, but my vote is still for injection. It seems like we are just moving that way and this is the next logical step before we end up there. Are there some specific issues we want to avoid with injecting a script in the header?

**Comment by nukulb** [comment]
@cdelcol

**Comment by nukulb** [comment]
Point is not to inject the user should be able to decide where and what page they load the webworks.js file. If we inject we will always need to inject without knowing if they want it or not.

**Comment by cdelcol** [comment]
I'm with @erikj54 but i've given up :). @jeffheifetz had many valid points during our early discussions and this accomplishes my main objective: download a sample that just works without modifications.

Speaking of:
- need to update Github samples
- need to update all of our test apps
- need to highlight this change in release notes in a BIG way

**Comment by nukulb** [comment]
and I will tweet it. :)

**Comment by ejzn** [comment]
This may sounds a little crazy, but what if we inject it on every page they use it? ie: inspect all html files in the packager + includes for a blackberry.\* namespace. If exists, inject into this HTML page.

If this is a large app, it could mean packaging would be a bit longer, but we could link all pages to the same webworks js file we put in for them.

**Comment by cdelcol** [comment]
Remote pages :). KISS.

**Comment by nukulb** [comment]
Firstly people make extensions with any namespace.
QNX auto has different namespaces. So the only way would be to check all namespaces in the APIs.
Obscure cases are also easily supported eg- What if the user wants to use the WebWorks API only on some part of app and he/she wants to load it at a certain point in time.

Secondly user content can be remote, how will you inspect that at package time?

Our current model provides all of these flexibilities with no added implementation complexities.
I cannot support doing parsing etc.. on user content as it will introduce lots of bugs.

Putting one constant line is no big deal for users I feel.

**Comment by ejzn** [comment]
Just an idea. Alright I give.

**Comment by rcruz** [comment]
How about using a script tag with local:/// as a primary way to load webworks.js for developers who want more control, and a secondary way to which autoinjects the script tag based on the domains specified in the whitelist. A loadwebworks=true attribute on the whitelist elements.

**Comment by nukulb** [comment]
I kind of hate it. Don't want to introduce more options for this case, more testing more everything. We should pick a way and just stick with it.
I think this happy medium provides the right mix of user experience and ease of implementation.

I vote we stick with our current approach that Bryan has implemented.

**Comment by kwallis** [comment]
+1

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jeffheifetz** [comment]
I want to apologize for starting this debate, I misread the description and thought the packager was searching through the bar or something equally bizarre. I think this implementation will suit our needs perfectly.

I would just love to see a packager warning if there already is a webworks-X.js file somewhere in the bar to help people in the transition.

**Comment by nukulb** [comment]
talking about issue
https://github.com/blackberry/BB10-WebWorks-Framework/issues/287

**Comment by bryanhiggins** [comment]
Amended my commit to warn if there are any webworks.js files in application source. If there is a chrome/webwork.js file, it will be overwritten.

**Comment by bryanhiggins** [comment]
Tested this with ripple - no issues.

Updated the sample apps:

https://github.com/bryanhiggins/BB10-WebWorks-Samples/commit/ea704c9b5bb5ccafeec5c74b2d6dcc0aa0a4c266

**Comment by nukulb** [comment]
r+

**Pull request closed without merging**
