### PR TITLE
Pull Req - Fix for GHI #85 [Packager error when output path is relative]

### PR DESCRIPTION
**Pull request by jamesjhedley**
Fixes BlackBerry GHI #85 - Packager error when output path is relative
+unit tests

### CODE REVIEW

**Comment by erhorim** [comment]
Tests passed in Win XP.

**Comment by EricLeiLi** [comment]
r+

**Comment by tracyli** [comment]
Tested in Mac and no issue found.

**Comment by erhorim** [comment]
SV&V tests passed, please merge.

**Pull request merged**
