### PR TITLE
Updated packager to use zygote process instead of weblauncher

### PR DESCRIPTION
**Pull request by rcruz**

### CODE REVIEW

**Comment by nukulb** [comment]
@rcruz - the backing store needs to be set to 8 instead of 12

_attr : { value : '12', var : 'WEBKIT_NUMBER_OF_BACKINGSTORE_TILES'}

for performance reason please include it here.

that line is in the same native-packager.js

**Comment by ishneur** [comment]
Tested on trunk 2628 by running slog2info and comparing startup time:
- An app packaged using this branch takes about 2.4 seconds to start up
- The same app packaged using the next branch takes about 2.8 seconds to start up
- The app packaged using this branch uses webkit_launcher as opposed to weblauncher

The improvement is about 400 milliseconds.

MANIFEST.MF for the app packaged using this branch contains:
Entry-Point: WEBKIT_NUMBER_OF_BACKINGSTORE_TILES=8 app/native/wwe
Entry-Point-Type: Qnx/WebKit

MANIFEST.MF for the app packaged using the next branch contains:
Entry-Point: WEBKIT_NUMBER_OF_BACKINGSTORE_TILES=12 app/native/wwe
Entry-Point-Type: Qnx/Elf

**Comment by jamesjhedley** [comment]
r+

**Comment by rcruz** [comment]
Merged manually

**Pull request merged**
